[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nidasaifi238", email = "nidasaifi238@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agentic-ai = "agentic_ai:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
